<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>
		Written by Peter Varo (c)2016
		http://github.com/petervaro/templang
	</string>
	<key>fileTypes</key>
	<array>
		<string>tl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\.*\(</string>
	<key>foldingStopMarker</key>
	<string>\.*\)</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>templang</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.element.tl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\$[^\s(){}\[\]]*)|([A-Z0-9-_]+)|([^\s(){}\[\]]*))</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.variable.tl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language.tl</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.function.name.tl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\))</string>
					<key>name</key>
					<string>meta.element.name.tl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#whitespace</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#attributes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literals</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\S+</string>
			<key>name</key>
			<string>invalid.illegal.text.tl</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attributes</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.attribute.tl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\$([^\s{}\[\]](?!\(\*))*)|(((?!\(\*)[^\s{}\[\]](?!\(\*))*))</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.type.special.tl</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.language.tl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\])</string>
					<key>name</key>
					<string>meta.attribute.name.tl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#whitespace</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#literals</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\[</string>
							<key>name</key>
							<string>invalid.illegal.symbol.tl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block.tl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.string.quote_braces.tl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;={)</string>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>string.quoted.single.literal.tl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\({|}|n|f|n|r|t|v|\\|0)</string>
							<key>name</key>
							<string>constant.character.escaped.tl</string>
						</dict>
						<dict>
							<key>match</key>
							<string>{</string>
							<key>name</key>
							<string>invalid.illegal.symbol.tl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>whitespace</key>
		<dict>
			<key>match</key>
			<string>\s|\n</string>
			<key>name</key>
			<string>meta.whitespace.tl</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tl</string>
	<key>uuid</key>
	<string>2A76B6DB-0CDE-4CE9-9D95-BB415D3EF755</string>
</dict>
</plist>
